spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: dly3230
    url: jdbc:mysql://localhost:3306/learn_database?characterEncoding=utf-8&useSSL=false
#mybatis的相关配置
mybatis:
  #mapper配置文件?
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: top.younote.tool.database.pojo
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    top.younote.learn.Mapper: debug